//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenDetails.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChildrenDetailsEntities : DbContext
    {
        public ChildrenDetailsEntities()
            : base("name=ChildrenDetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChildrenDetail> ChildrenDetails { get; set; }
        public DbSet<ChildrenStatu> ChildrenStatus { get; set; }
        public DbSet<ChildrenType> ChildrenTypes { get; set; }
        public DbSet<ChildrenFileUpload> ChildrenFileUploads { get; set; }
    }
}
