//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChildrenDetail
    {
        public int ID { get; set; }

        [Required]
        [DisplayName("Child Last Name")]
        public string Child_Last_Name { get; set; }

        [Required]
        [DisplayName("Child First Name")]
        public string Child_First_Name { get; set; }

        [Required]
        public string Child_Gender { get; set; }

        [Required]
        [DisplayName("Child Birth Date")]
        public System.DateTime Child_Birth_Date { get; set; }

        [Required]
        public int Child_Status { get; set; }

        [Required]
        public string Child_Address { get; set; }

        [Required]
        public int Child_Type { get; set; }

        [Required]
        public string Parent1_Last_Name { get; set; }

        [Required]
        public string Parent1_First_Name { get; set; }

        [Required]
        public string Parent1_Private { get; set; }

        [Required]
        public string Parent1_Gender { get; set; }

        [Required]
        public string Parent1_Child_Relation { get; set; }

        [Required]
        public string Parent1_Address { get; set; }

        [Required]
        public string Parent1_Unit { get; set; }

        [Required]
        public string Parent1_City { get; set; }

        [Required]
        public string Parent1_Province { get; set; }

        [Required]
        public string Parent1_Postal_Code { get; set; }

        [Required]
        public string Parent1_Home_Phone { get; set; }

        [Required]
        public string Parent1_Work_Phone { get; set; }

        [Required]
        public string Parent1_Cell_Phone { get; set; }

        [Required]
        public string Parent1_Email { get; set; }

        [Required]
        public bool Parent1_Primary_Email { get; set; }

        [Required]
        public string Parent1_Comments { get; set; }

        [Required]
        public string Parent1_Special_Custody { get; set; }

        [Required]
        public string Parent2_Last_Name { get; set; }

        [Required]
        public string Parent2_First_Name { get; set; }

        [Required]
        public string Parent2_Private { get; set; }

        [Required]
        public string Parent2_Gender { get; set; }

        [Required]
        public string Parent2_Child_Relation { get; set; }

        [Required]
        public string Parent2_Address { get; set; }

        [Required]
        public string Parent2_Unit { get; set; }

        [Required]
        public string Parent2_City { get; set; }

        [Required]
        public string Parent2_Province { get; set; }

        [Required]
        public string Parent2_Postal_Code { get; set; }

        [Required]
        public string Parent2_Home_Phone { get; set; }

        [Required]
        public string Parent2_Work_Phone { get; set; }

        [Required]
        public string Parent2_Cell_Phone { get; set; }

        [Required]
        public string Parent2_Email { get; set; }

        [Required]
        public bool Parent2_Primary_Email { get; set; }

        [Required]
        public string Parent2_Comments { get; set; }

        [Required]
        public string Parent2_Special_Custody { get; set; }

        [Required]
        public string Sibling_Name { get; set; }

        [Required]
        public int Sibling_Age { get; set; }

        [Required]
        public string Sibling_Gender { get; set; }

        [Required]
        [DisplayName("Contact1 Name")]
        public string Contact1_Name { get; set; }

        [Required]
        [Phone]
        [DisplayName("Contact1 Phone")]
        public string Contact1_Phone { get; set; }

        [Required]
        [EmailAddress]
        [DisplayName("Contact1 Email")]
        public string Contact1_Email { get; set; }

        [Required]
        public string Contact1_Address { get; set; }

        [Required]
        public string Contact1_Relationship { get; set; }

        [Required]
        public string Contact2_Name { get; set; }

        [Required]
        public string Contact2_Phone { get; set; }

        [Required]
        public string Contact2_Email { get; set; }

        [Required]
        public string Contact2_Address { get; set; }

        [Required]
        public string Contact2_Relationship { get; set; }

        [Required]
        public string Contact3_Name { get; set; }

        [Required]
        public string Contact3_Phone { get; set; }

        [Required]
        public string Contact3_Email { get; set; }

        [Required]
        public string Contact3_Address { get; set; }

        [Required]
        public string Contact3_Relationship { get; set; }

        [Required]
        public string Contact4_Name { get; set; }

        [Required]
        public string Contact4_Phone { get; set; }

        [Required]
        public string Contact4_Email { get; set; }

        [Required]
        public string Contact4_Address { get; set; }

        [Required]
        public string Contact4_Relationship { get; set; }

        public List<ChildrenDetail> ChildrenDetails { get; set; }
        public ChildrenDetail SelectedCustomer { get; set; }
        public string DisplayMode { get; set; }
    }
}
